First functiona version with provisioning.

diff --git a/crates/base/dev b/crates/base/dev
--- a/crates/base/dev
+++ b/crates/base/dev
@@ -1,69 +1,79 @@
+if [[ -z "$BASE_USER" ]]; then
+	echo -e "Required variable BASE_USER unset; aborting"
+	exit 1
+fi
+
+if [[ -z "$BASE_HOME" ]]; then
+	echo -e "Required variable BASE_HOME unset; aborting"
+	exit 1
+fi
+
 echo -e "\n~~~ Verifying Git ~~~\n"
 
 GIT=$(which git)
 if [[ $? -ne 0 ]]; then
 	echo -e "No Git detected; check and retry"
-	exit 11 
+	exit 1
 fi
 GITVER=$(git --version)
 echo -e "Found Git, $GITVER"
 
+if [[ -z "$GIT_USER" ]]; then
+    GIT_USER="Michael Skelton"
+fi
+
+if [[ -z "$GIT_EMAIL" ]]; then
+    GIT_USER="skelton.michael@gmail.com"
+fi
+
 echo -e "* Setting .gitconfig *"
-$GIT config --global --add user.name "Michael Skelton"
-$GIT config --global --add user.email "mskelton@bloomberg.net" # TO DO ~> parameterize
+sudo -u $BASE_USER $GIT config --global --add user.name $GIT_USER
+sudo -u $BASE_USER $GIT config --global --add user.email $GIT_EMAIL
 
-if [[ ! -d $HOME/Code ]]; then
+if [[ ! -d $BASE_HOME/Code ]]; then
 	echo -e "~~~ Creating ~/Code directory ~~~"
-	mkdir -p $HOME/Code/{linux,sk3l}
+	sudo -u $BASE_USER mkdir -p $BASE_HOME/Code
 fi
 
-GITHUB=https://github.com/sk3l
+#GITHUB=https://github.com/sk3l
 
-SRCPATH="$HOME/Code/sk3l"
-echo -e "\n~~~ Pulling down source repos ~~~"
+#SRCPATH="$HOME/Code/sk3l"
+#echo -e "\n~~~ Pulling down source repos ~~~"
 
-if [[ ! -d $SRCPATH/sk3lshell ]]; then
-    echo -e "\n* cloning sk3lshell *"
-    if ! $GIT clone -c http.sslVerify=false $GITHUB/sk3lshell $SRCPATH/sk3lshell; then
-	    echo -e "Unable to clone sk3lshell; aborting"
-	    return 1 
-    fi
-fi
+#if [[ ! -d $SRCPATH/sk3lshell ]]; then
+#    echo -e "\n* cloning sk3lshell *"
+#    if ! $GIT clone -c http.sslVerify=false $GITHUB/sk3lshell $SRCPATH/sk3lshell; then
+#	    echo -e "Unable to clone sk3lshell; aborting"
+#	    return 1
+#    fi
+#fi
 
-if [[ ! -d $SRCPATH/tmux-conf ]]; then
-    echo -e "\n* cloning tmux-conf*"
-    if ! $GIT clone -c http.sslVerify=false $GITHUB/tmux-conf $SRCPATH/tmux-conf; then
-	    echo -e "Unable to clone tmux-conf; aborting"
-	    return 1 
-    fi
-fi
-
-if [[ ! -d $SRCPATH/vim-conf ]]; then
-    echo -e "\n* cloning vim-conf*"
-    if ! $GIT clone -c http.sslVerify=false $GITHUB/vim-conf $SRCPATH/vim-conf; then
-	    echo -e "Unable to clone vim-conf; aborting"
-	    return 1 
-    fi
-fi
+#if [[ ! -d $SRCPATH/tmux-conf ]]; then
+#    echo -e "\n* cloning tmux-conf*"
+#    if ! $GIT clone -c http.sslVerify=false $GITHUB/tmux-conf $SRCPATH/tmux-conf; then
+#	    echo -e "Unable to clone tmux-conf; aborting"
+#	    return 1
+#    fi
+#fi
+#
+#if [[ ! -d $SRCPATH/vim-conf ]]; then
+#    echo -e "\n* cloning vim-conf*"
+#    if ! $GIT clone -c http.sslVerify=false $GITHUB/vim-conf $SRCPATH/vim-conf; then
+#	    echo -e "Unable to clone vim-conf; aborting"
+#	    return 1
+#    fi
+#fi
 
 echo -e "\n~~~ Installing ViM config ~~~\n"
 
-[[ ! -d $HOME/.vim ]] && mkdir $HOME/.vim
+[[ ! -d $BASE_HOME/.vim ]] && mkdir $BASE_HOME/.vim
 
-cp $SRCPATH/vim-conf/conf/.vimrc $HOME 
-cp -R $SRCPATH/vim-conf/conf $HOME/.vim/
-cp -R $SRCPATH/vim-conf/colors $HOME/.vim/
+cp modules/vim-conf/conf/.vimrc $BASE_HOME
+cp -R modules/vim-conf/conf $BASE_HOME/.vim/
+cp -R modules/vim-conf/colors $BASE_HOME/.vim/
 
 echo -e "\n~~~ Installing tmux config ~~~\n"
 
-cp $SRCPATH/tmux-conf/.tmux.conf $HOME 
+cp modules/tmux-conf/.tmux.conf $BASE_HOME
 
-echo -e "\n~~~ Installing shell resource files ~~~\n"
-
-cp $SRCPATH/sk3lshell/dot-files/.bashrc $HOME 
-
-if [[ -f "$SRCPATH/sk3lshell/dot-files/.bashrc_local_$TYPE" ]]; then
-    echo -e "* Found distro-specific shell resource file for $TYPE; installing *"
-    cp "$SRCPATH/sk3lshell/dot-files/.bashrc_local_$TYPE" $HOME/
-fi
 
diff --git a/crates/base/user b/crates/base/user
--- a/crates/base/user
+++ b/crates/base/user
@@ -1,22 +1,37 @@
 
-if [[ ! -z $BASE_USER ]]; then
+if [[ -z "$BASE_USER" ]]; then
     BASE_USER=mskelton
 fi
 
-# Create base user 
-echo -e "\n~~~ Creating base uer login ${BASE_USER}  ~~~\n"
-if getent passwd ${BASE_USER} > /dev/null; then
-    echo -e "Base user ${BASE_USER} already exists"
-else
-    if ! useradd -m -s /bin/bash $BASE_USER > /dev/null; then
-        echo -e "Failed creating base user ${BASE_USER}"
-        exit 1
-    fi     
+if [[ -z "$BASE_HOME" ]]; then
+    BASE_HOME=/home/$BASE_USER
 fi
 
-# Add user to admin/wheel 
-echo -e "\n~~~ Adding base user ${BASE_USER} to admin  ~~~\n"
+# Create base user
+echo -e "   - Creating base user login ${BASE_USER}"
+if getent passwd ${BASE_USER} > /dev/null; then
+    echo -e "   - Base user ${BASE_USER} already exists"
+else
+    if ! useradd -m -s /bin/bash $BASE_USER > /dev/null; then
+        echo -e "!!! Failed creating base user ${BASE_USER} !!!\n"
+        exit 1
+    fi
+fi
+
+# Add user to groups
+echo -e "   - Adding base user ${BASE_USER} to wheel"
 if ! usermod -a -G wheel $BASE_USER; then
-    echo -e "Failed adding base user ${BASE_USER} groups"
+    echo -e "!!! Failed adding base user ${BASE_USER} groups !!!\n"
     exit 1
-fi     
+fi
+
+# Configure user's shell
+echo -e "   - Configuring base user's shell"
+
+cp modules/sk3lshell/dot-files/.bashrc $BASE_HOME
+
+if [[ -f "modules/sk3lshell/dot-files/.bashrc_local_$OS_TYPE" ]]; then
+    echo -e "* Found distro-specific shell resource file for $OS_TYPE; installing *"
+    cp "modules/sk3lshell/dot-files/.bashrc_local_$OS_TYPE" $BASE_HOME/
+fi
+
