Formatting improvements.

diff --git a/crates/centos/centos_base b/crates/centos/centos_base
--- a/crates/centos/centos_base
+++ b/crates/centos/centos_base
@@ -1,15 +1,15 @@
 
 # Install SCL, or fail
-echo -e "   - Enabling Red Hat SCL repository"
-if ! yum-config-manager --enable rhel-server-rhscl-7-rpms; then
-    echo -e "!!! Failed enabling Red Hat SCL !!!\n"
+log_info "    - Enabling Red Hat SCL repository"
+if ! yum install -y centos-release-scl; then
+    log_error "!!! Failed enabling Red Hat SCL !!!\n"
     exit 1
 fi
 
 # Install EPEL, or fail
-echo -e " - Enabling Red Hat EPEL repository"
-if ! yum -y install epel-release; then
-    echo -e "!!! Failed enabling Red Hat EPEL !!!\n"
+log_info "    - Enabling Red Hat EPEL repository"
+if ! yum install -y epel-release; then
+    log_error "!!! Failed enabling Red Hat EPEL !!!\n"
     exit 1
 fi
 
diff --git a/crates/rhel/rhel_base b/crates/rhel/rhel_base
--- a/crates/rhel/rhel_base
+++ b/crates/rhel/rhel_base
@@ -1,15 +1,15 @@
 
 # Install SCL, or fail
-echo -e "\n~~~ Enabling Red Hat SCL repository  ~~~\n"
+log_info "\n~~~ Enabling Red Hat SCL repository  ~~~\n"
 if ! yum-config-manager --enable rhel-server-rhscl-7-rpms; then
-    echo -e "!!! Failed enabling Red Hat SCL !!!"
+    log_error "!!! Failed enabling Red Hat SCL !!!"
     exit 1
 fi
 
 # Install EPEL, or fail
-echo -e "\n~~~ Enabling Red Hat EPEL repository  ~~~\n"
-if ! yum -y install epel-release; then
-    echo -e "!!! Failed enabling Red Hat EPEL !!!"
+log_info "\n~~~ Enabling Red Hat EPEL repository  ~~~\n"
+if ! yum install -y epel-release; then
+    log_error "!!! Failed enabling Red Hat EPEL !!!"
     exit 1
 fi
 
diff --git a/crates/rhel/rhel_dev b/crates/rhel/rhel_dev
--- a/crates/rhel/rhel_dev
+++ b/crates/rhel/rhel_dev
@@ -1,10 +1,25 @@
 
-echo -e "\n~~~ Enabling Red Hat SCL repository  ~~~\n"
-yum-config-manager --enable rhel-server-rhscl-7-rpms
+info "\n~~~ Installing CentOS dev packages  ~~~\n"
+yum install -y \
+    cmake3 \
+    devtoolset-7-gcc-c++ \
+    devtoolset-7-gdb \
+    llvm-toolset-7-clang \
+    llvm-toolset-7-clang-tools-extra \
+    python36 \
+    python36-pip \
+    python36-setuptools \
+    rh-git29-git \
 
-echo -e "\n~~~ Enabling Red Hat EPEL repository  ~~~\n"
-yum -y install epel-release
+if [[ $? -ne 0 ]];then
+    error "!!! Failed installing CentOS dev packages; aborting !!!"
+    exit 1
+fi
 
-return 0 
+info "\n~~~ Activate SCL packages  ~~~\n"
+cat <<EOF> /etc/profile.d/scl_enable.sh
+#!/bin/bash
+source scl_source enable rh-git29
+EOF
 
-
+. /opt/rh/rh-git29/enable
