Simplify calling of 'crates' scripts

diff --git a/crates/base_user b/crates/base_user
--- a/crates/base_user
+++ b/crates/base_user
@@ -18,11 +18,13 @@ else
     fi
 fi
 
-# Add user to groups
-log_info "   - Adding base user ${BASE_USER} to wheel"
-if ! usermod -a -G wheel $BASE_USER; then
-    log_error "!!! Failed adding base user ${BASE_USER} groups !!!\n"
-    exit 1
+if [[ ! -z "$BASE_GROUPS" ]]; then
+    # Add user to groups
+    log_info "   - Adding base user ${BASE_USER} to groups ${BASE_GROUPS}"
+    if ! usermod -a -G ${BASE_GROUPS} $BASE_USER; then
+        log_error "!!! Failed adding base user ${BASE_USER} groups !!!\n"
+        exit 1
+    fi
 fi
 
 # Configure user's shell
