Refactor Ubuntu crates

diff --git a/crates/ubuntu_dev b/crates/ubuntu_dev
--- a/crates/ubuntu_dev
+++ b/crates/ubuntu_dev
@@ -1,72 +1,136 @@
+DEV_PACKAGES=(
+    "cmake"
+    "build-essential"
+    "git"
+    "npm"
+    "python3-pip"
+    "python3-setuptools"
+)
 
-log_info "\n~~~ Installing Ubuntu dev repositories ~~~\n"
+log_info "\n(movein)[I] - Installing Ubuntu dev repositories"
 
-# Docker repos
-log_info "    - Installing Docker repo GPG key"
-if ! wget -O - https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -;then
-    log_error "!!! Failed installing GPG keys for Ubuntu dev repo Docker; aborting !!!"
-    exit 1
+inst_docker=$(prompt_user "install Docker")
+if [[ ${inst_docker} -eq 1 ]];then
+    # Docker repos
+    log_info "            - Installing Docker repo GPG key"
+    CMD="wget -O - https://download.docker.com/linux/ubuntu/gpg | apt-key add -"
+    run_as_sudo "${CMD}" 1
+    if [[ $? -ne 0 ]];then
+        log_error "(movein)[E] - Failed installing GPG keys for Ubuntu dev repo Docker; aborting"
+        return 1
+    fi
+
+    log_info "            - Installing Docker repo"
+    CMD="echo \"deb [arch=amd64] https://download.docker.com/linux/ubuntu disco stable\"\
+      > /etc/apt/sources.list.d/docker.list"
+    run_as_sudo "${CMD}" 1
+    if [[ $? -ne 0 ]];then
+        log_error "(movein)[E] - Failed installing Ubuntu dev repo Docker; aborting"
+        return 1
+    fi
+    DEV_PACKAGES+=( "docker-ce" )
 fi
 
-log_info "    - Installing Docker repo"
-if ! echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu disco stable" > /etc/apt/sources.list.d/docker.list;then
-    log_error "!!! Failed installing Ubuntu dev repo Docker; aborting !!!"
-    exit 1
+inst_clang=$(prompt_user "install Clang")
+if [[ ${inst_clang} -eq 1 ]];then
+    # Clang repos
+    log_info "            - Installing Clang repo GPG key"
+    CMD="wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -"
+    run_as_sudo "${CMD}" 1
+    if [[ $? -ne 0 ]];then
+        log_error "(movein)[E] - Failed installing GPG keys for Ubuntu dev repo LLVM; aborting"
+        return 1
+    fi
+
+    log_info "            - Installing Clang repo"
+    CMD="echo \"deb http://apt.llvm.org/disco/ llvm-toolchain-disco main\"\
+       > /etc/apt/sources.list.d/clang.list"
+    run_as_sudo "${CMD}" 1
+    if [[ $? -ne 0 ]];then
+        log_error "(movein)[E] - Failed installing Ubuntu dev repo LLVM; aborting"
+        return 1
+    fi
+    DEV_PACKAGES+=( "clang-format" )
+    DEV_PACKAGES+=( "clang-tidy" )
+    DEV_PACKAGES+=( "clang-tools" )
+    DEV_PACKAGES+=( "clang" )
 fi
 
-log_info "\n~~~ Updating Ubuntu apt repos  ~~~\n"
-if ! apt-get update; then
-    log_error "!!! Failed updating Ubuntu apt data !!!"
-    exit 1
-fi
-
-# Clang repos
-log_info "    - Installing Clang repo GPG key"
-if ! wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -;then
-    log_error "!!! Failed installing GPG keys for Ubuntu dev repo LLVM; aborting !!!"
-    exit 1
-fi
-
-log_info "    - Installing Clang repo"
-if ! echo "deb http://apt.llvm.org/disco/ llvm-toolchain-disco main" > /etc/apt/sources.list.d/clang.list;then
-    log_error "!!! Failed installing Ubuntu dev repo LLVM; aborting !!!"
-    exit 1
-fi
-
-#log_info "    - Installing Clang source repo"
-#if ! add-apt-repository "deb-src http://apt.llvm.org/disco/ llvm-toolchain-disco main";then
-#    log_error "!!! Failed installing Ubuntu dev-src repo LLVM; aborting !!!"
-#    exit 1
-#fi
-
-log_info "\n~~~ Updating Ubuntu apt repos  ~~~\n"
-if ! apt-get update; then
-    log_error "!!! Failed updating Ubuntu apt data !!!"
-    exit 1
-fi
-
-log_info "\n~~~ Installing Ubuntu dev packages  ~~~\n"
-apt-get install -y \
-    cmake \
-    build-essential \
-    clang-format \
-    clang-tidy \
-    clang-tools \
-    clang \
-    docker-ce \
-    npm \
-    python3-pip \
-    python3-setuptools \
-    vim-nox
-if [[ $? -ne 0 ]];then
-    log_error "!!! Failed installing Ubuntu dev packages; aborting !!!"
-    exit 1
-fi
-
-if [[ ! -z "$BASE_USER" ]]; then
-    log_info "\n~~~ Adding ${BASE_USER} to docker group ~~~\n"
-    if ! usermod -a -G docker $BASE_USER; then
-        log_error "!!! Failed adding base user ${BASE_USER} to docker group !!!\n"
-        exit 1
+if [[ -z ${apt_proxy} ]];then
+    set_apt_proxy=$(prompt_user "set apt HTTP proxy")
+    if [[ ${set_apt_proxy} -eq 1 ]];then
+        export apt_proxy="http_proxy=$(read_user_variable 'apt HTTP proxy')"
     fi
 fi
+
+log_info "\n(movein)[I] - Updating Ubuntu apt repos"
+CMD="${apt_proxy} apt update"
+run_as_sudo "${CMD}" 1
+if [[ $? -ne 0 ]];then
+    log_error "(movein)[E] - Failed updating Ubuntu apt data; aborting"
+    return 1
+fi
+
+INSTALL_PACKAGES=()
+log_info "\n(movein)[I] - Checking Ubuntu dev packages"
+for pkg in ${DEV_PACKAGES[@]};
+do
+    PKG_NAME="            - $pkg"
+    if ! dpkg --no-pager -l $pkg > /dev/null 2>&1;then
+        PKG_NAME+=" (missing; will install)"
+        INSTALL_PACKAGES+=( $pkg )
+    else
+        PKG_NAME+=" (exists)"
+    fi
+    log_info "${PKG_NAME}"
+done
+
+log_info "\n(movein)[I] - Installing Ubuntu dev packages"
+CMD="${apt_proxy} apt-get install -y ${INSTALL_PACKAGES[@]}"
+run_as_sudo "${CMD}" 1
+if [[ $? -ne 0 ]];then
+    log_error "\n(movein)[EE] - Failed installing Ubuntu dev packages; aborting"
+    return 1
+fi
+
+EDITOR="nvim"
+EDITOR_PATH="/usr/local/sbin"
+log_info "\n(movein)[I] - Installing Ubuntu dev editor"
+if [[ ! -L "${EDITOR_PATH}/${EDITOR}" ]];then
+    EDITOR_URL="https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage"
+    CMD="wget -O ${EDITOR_PATH}/nvim.appimage ${EDITOR_URL}"
+    run_as_sudo "${CMD}" 1
+    if [[ $? -ne 0 ]];then
+        log_error "\n(movein)[EE] - Failed installing Ubuntu dev editor; aborting"
+        return 1
+    fi
+
+    CMD="ln -s ${EDITOR_PATH}/nvim.appimage ${EDITOR_PATH}/nvim;"
+    run_as_sudo "${CMD}" 1
+    if [[ $? -ne 0 ]];then
+        log_error "\n(movein)[EE] - Failed installing Ubuntu dev editor; aborting"
+        return 1
+    fi
+
+fi
+log_info "\n(movein)[I] - Successfully installed Ubuntu dev packages"
+
+if [[ $inst_docker == "1" && ! -z "$BASE_USER" ]]; then
+    log_info "            - Adding ${BASE_USER} to docker group"
+    CMD="usermod -a -G docker $BASE_USER"
+    run_as_sudo "${CMD}" 1
+    if [[ $? -ne 0 ]];then
+         log_error "\n(movein)[EE] - Failed adding base user ${BASE_USER} to docker group"
+         return 1
+     fi
+ fi
+
+if [[ $inst_docker == "1" && ! -z "$BASE_USER" ]]; then
+    log_info "            - Adding ${BASE_USER} to docker group"
+    CMD="usermod -a -G docker $BASE_USER"
+    run_as_sudo "${CMD}" 1
+    if [[ $? -ne 0 ]];then
+         log_error "\n(movein)[EE] - Failed adding base user ${BASE_USER} to docker group"
+         return 1
+     fi
+ fi
