Updates to Ubuntu/Debian crates.

diff --git a/crates/ubuntu_base b/crates/ubuntu_base
--- a/crates/ubuntu_base
+++ b/crates/ubuntu_base
@@ -1,21 +1,61 @@
 
 # Add additional source repos here
 #
-log_info "\n~~~ Installing Ubuntu base packages  ~~~\n"
-apt-get install -y \
-    apt-transport-https \
-    ca-certificates \
-    curl \
-    software-properties-common
+BASE_PACKAGES=(
+    "apt-transport-https"
+    "ca-certificates"
+    "coreutils"
+    "curl"
+    "grep"
+    "fuse"
+    "nautilus"
+    "net-tools"
+    "sed"
+    "sshfs"
+    "smbclient"
+    "software-properties-common"
+)
 
+INSTALL_PACKAGES=()
+log_info "\n(movein)[I] - Checking Ubuntu base packages"
+for pkg in ${BASE_PACKAGES[@]};
+do
+    PKG_NAME="            - $pkg"
+    if ! dpkg --no-pager -l $pkg > /dev/null 2>&1;then
+        PKG_NAME+=" (missing; will install)"
+        INSTALL_PACKAGES+=( $pkg )
+    else
+        PKG_NAME+=" (exists)"
+    fi
+    log_info "${PKG_NAME}"
+done
+
+log_info "\n(movein)[I] - Installing Ubuntu base packages"
+CMD="apt-get install -y ${INSTALL_PACKAGES[@]}"
+run_as_sudo "${CMD}" 1
 if [[ $? -ne 0 ]];then
-    log_error "!!! Failed installing Ubuntu base packages; aborting !!!"
-    exit 1
+    log_error "\n(movein)[EE] - Failed installing Ubuntu base packages; aborting"
+    return 1
 fi
+log_info "\n(movein)[I] - Successfully installed Ubuntu base packages"
+
+log_info "\n(movein)[I] - Executing Ubuntu base customizations"
 
 # Tweak sudoers to permit `sudo` group members paswordless execution
-log_info "\n~~~ Executing Ubuntu base customizations~~~\n"
-if ! sed "s/%sudo.*/%sudo    ALL=(ALL:ALL) NOPASSWD: ALL/" -iBAK /etc/sudoers;then
-    log_error "!!! Failed applying Ubuntu base sudo customization; aborting !!!"
-    exit 1
+CUSTOM_NAME="            - sudo without password"
+CMD="grep -q \"sudo\s*ALL=(ALL) ALL\s*$\" /etc/sudoers"
+run_as_sudo "${CMD}"
+if [[ $? -eq 0 ]];then
+    CMD="sed \"s/%sudo.*/%sudo    ALL=(ALL:ALL) NOPASSWD: ALL/\" -iBAK /etc/sudoers"
+    run_as_sudo "${CMD}"
+    if [[ $? -ne 0 ]];then
+        CUSTOM_NAME+=" (failed)"
+    else
+        CUSTOM_NAME+=" (success)"
+    fi
+else
+    CUSTOM_NAME+=" (exists)"
 fi
+log_info "${CUSTOM_NAME}"
+
+log_info "\n(movein)[I] - Successfully set Ubuntu base customizations"
